swagger: '2.0'
info:
  version: "1.0.0"
  title: "todo list"
  description: "simple todo list experiment"
host: api.org
schemes: 
  - https
basePath: /
paths:
  /task:
    get:
      summary: "Get all tasks"
      responses:
        '200':
          description: Success response
    post:
      summary: post a new task
      description: post a new task
      responses:
        200:
          description: Success
    delete:
      summary: delete a task
      description: delete a task
      responses:
        200:
          description: Success
          
    
    