info:
  version: "1.0.0"
  title: "todo list"
  description: "simple todo list experiment"
host: hydrus.com
schemes: 
  - https
basePath: /
paths:
  /task:
    get:
      summary: "Get all tasks"
      responses:
        200:
          description: Success response
    post:
      summary: post a new task
      description: post a new task
      parameters: 
      - in: "body"
        name: "task"
        description: "Task object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/task"
      responses:
        200:
          description: Success
swagger: '2.0'

definitions:
  task :
    type: "object"
    description: "this is object desc"
    properties:
      id:
        type: "object"
        format: "http://schema.org/identifier"
      title:
        type: "object"
        description: "Title  of the task"
      timeLimit:
        type: "object"
        format: "date-time"
      desc:
        type: "object"
        description: detail of the task 
      status:
        type: "string"
        description: "Task status "
        enum: 
        - "Pending"
        - "Started"
        - "Completed"
        
        

          
    
    